apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-management
spec:
  replicas: {{ .Values.customerManagement.replicas }}
  selector:
    matchLabels:
      app: customer-management
  template:
    metadata:
      labels:
        app: customer-management
    spec:
      containers:
      - name: customer-management
        image: {{ .Values.customerManagement.image }}
        ports:
        - containerPort: {{ .Values.customerManagement.port }}
        envFrom:
        - configMapRef:
            name: customer-management-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
