apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-management
spec:
  replicas: {{ .Values.customerManagement.replicas }}
  selector:
    matchLabels:
      app: customer-management
  template:
    metadata:
      labels:
        app: customer-management
    spec:
      containers:
      - name: customer-management
        image: {{ .Values.customerManagement.image }}
        ports:
        - containerPort: {{ .Values.customerManagement.port }}
        envFrom:
        - configMapRef:
            name: customer-management-config
      imagePullSecrets:
      - name: ecr-registry-secret
