apiVersion: v1
kind: Service
metadata:
  name: customer-management-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /purchases
spec:
  selector:
    app: customer-management
  ports:
  - protocol: TCP
    port: {{ .Values.customerManagement.port }}
    targetPort: {{ .Values.customerManagement.port }}
