apiVersion: v1
kind: Service
metadata:
  name: customer-web-server-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /getAllUserBuys
spec:
  selector:
    app: customer-web-server
  ports:
  - protocol: TCP
    port: {{ .Values.customerWebServer.port }}
    targetPort: {{ .Values.customerWebServer.port }}
