apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image }}
        ports:
        - containerPort: {{ .Values.frontend.port }}
        env:
        - name: CUSTOMER_WEB_SERVER_URL
          value: {{ .Values.frontend.customerWebServerUrl | quote }}
        - name: CUSTOMER_MANAGEMENT_URL
          value: {{ .Values.frontend.customerManagementUrl | quote }}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      imagePullSecrets:
      - name: ecr-registry-secret
