apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: {{ .Values.mongo.storage }}
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "{{ .Values.mongo.hostPath }}"
